INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(1,  'Bethina Jacklin',  'bjacklin0@nih.gov')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(2,  'Kameko Nesterov',  'knesterov1@ucsd.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(3,  'Arnoldo Nother',  'another2@zimbio.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(4,  'Waldo Cossor',  'wcossor3@uol.com.br')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(5,  'Godfree Redfield',  'gredfield4@hc360.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(6,  'Harriett Markovic',  'hmarkovic5@imageshack.us')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(7,  'Celestia Pfeifer',  'cpfeifer6@alibaba.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(8,  'Bobbie Doni',  'bdoni7@pen.io')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(9,  'Ali Rowan',  'arowan8@newsvine.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(10,  'Erek Cream',  'ecream9@bing.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(11,  'Currie Melling',  'cmellinga@godaddy.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(12,  'Carl Stener',  'cstenerb@tmall.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(13,  'Lamond Gutridge',  'lgutridgec@alibaba.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(14,  'Myles Dumbare',  'mdumbared@springer.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(15,  'Charlot Baulk',  'cbaulke@sitemeter.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(16,  'Corty Lackmann',  'clackmannf@telegraph.co.uk')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(17,  'Felix Manes',  'fmanesg@google.co.uk')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(18,  'Akim Dennick',  'adennickh@time.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(19,  'Randa Vant',  'rvanti@mapy.cz')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(20,  'Georgeta Gedge',  'ggedgej@china.com.cn')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(21,  'Trefor Luker',  'tlukerk@cornell.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(22,  'Madalyn Blaise',  'mblaisel@indiegogo.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(23,  'Clim Rooper',  'crooperm@bizjournals.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(24,  'Corey Cosgrove',  'ccosgroven@wisc.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(25,  'Brittaney Castanho',  'bcastanhoo@gnu.org')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(26,  'Kerri MacCleod',  'kmaccleodp@pagesperso-orange.fr')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(27,  'Rob Iacoviello',  'riacovielloq@twitpic.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(28,  'Eudora Laidler',  'elaidlerr@cdc.gov')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(29,  'Lanette Derell',  'lderells@loc.gov')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(30,  'Ike Loftie',  'iloftiet@blogspot.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(31,  'Gwyneth Doddridge',  'gdoddridgeu@disqus.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(32,  'Byrann Willatts',  'bwillattsv@simplemachines.org')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(33,  'Auberta Polle',  'apollew@go.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(34,  'Humphrey Masdin',  'hmasdinx@ning.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(35,  'Enid Geroldi',  'egeroldiy@hao123.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(36,  'Ernestus Huson',  'ehusonz@goo.ne.jp')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(37,  'Debby Ollerearnshaw',  'dollerearnshaw10@biblegateway.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(38,  'Carlin Weeke',  'cweeke11@google.cn')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(39,  'Imogene Denzey',  'idenzey12@mashable.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(40,  'Sosanna Edgson',  'sedgson13@mayoclinic.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(41,  'Dayna McMeeking',  'dmcmeeking14@taobao.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(42,  'Abe Playfair',  'aplayfair15@mit.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(43,  'Raquela Finders',  'rfinders16@disqus.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(44,  'Easter Bussy',  'ebussy17@unc.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(45,  'Torrence Yeldon',  'tyeldon18@dailymail.co.uk')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(46,  'Minne Darch',  'mdarch19@shareasale.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(47,  'Meade McCotter',  'mmccotter1a@forbes.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(48,  'Wallis Boutton',  'wboutton1b@networkadvertising.org')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(49,  'Dominick Broadbury',  'dbroadbury1c@wordpress.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(50,  'Zachary Huot',  'zhuot1d@g.co')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(51,  'Clark Lorentz',  'clorentz1e@com.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(52,  'Evey Sperwell',  'esperwell1f@gnu.org')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(53,  'Toby Jelliman',  'tjelliman1g@xing.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(54,  'Rubie Collopy',  'rocollopy1h@google.pl')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(55,  'Clarabelle Tedstone',  'ctedstone1i@toplist.cz')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(56,  'Gerald Rheaume',  'grheaume1j@unblog.fr')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(57,  'Allyn Roycroft',  'aroycroft1k@canalblog.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(58,  'Debee Harmes',  'dharmes1l@phpbb.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(59,  'Shelba Capell',  'scapell1m@tripadvisor.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(60,  'Aggy Stepney',  'astepney1n@dot.gov')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(61,  'Susanna Halliwell',  'shalliwell1o@exblog.jp')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(62,  'Heinrick Georger',  'hgeorger1p@hostgator.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(63,  'Orelle Georgius',  'ogeorgius1q@businessweek.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(64,  'Vincenz Hegerty',  'vhegerty1r@multiply.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(65,  'Benni Basley',  'bbasley1s@pbs.org')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(66,  'Mozes Askham',  'maskham1t@wiley.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(67,  'Jessie Pickthall',  'jpickthall1u@reuters.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(68,  'Dav Gorham',  'dgorham1v@amazon.co.uk')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(69,  'Georgie Megany',  'gmegany1w@feedburner.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(70,  'Dannye Bygott',  'dbygott1x@telegraph.co.uk')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(71,  'Vicky Mackstead',  'vmackstead1y@chron.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(72,  'Bil Paff',  'bpaff1z@ning.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(73,  'Skip Emery',  'semery20@slashdot.org')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(74,  'Rikki Ashelford',  'rashelford21@google.ca')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(75,  'Christoph McGucken',  'cmcgucken22@washington.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(76,  'Enoch Duley',  'eduley23@spiegel.de')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(77,  'Osmond Nicely',  'onicely24@flavors.me')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(78,  'Gard French',  'gfrench25@abc.net.au')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(79,  'Katina Harbison',  'kharbison26@ucla.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(80,  'Clay Buxcey',  'cbuxcey27@arstechnica.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(81,  'Glenden Springtorp',  'gspringtorp28@wufoo.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(82,  'Cherise Bowkley',  'cbowkley29@arstechnica.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(83,  'Dante Butte',  'dbutte2a@tmall.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(84,  'Quint Careswell',  'qcareswell2b@topsy.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(85,  'Vinita Ithell',  'vithell2c@delicious.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(86,  'Taffy Norwood',  'tnorwood2d@studiopress.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(87,  'Philippe Chawner',  'pchawner2e@kickstarter.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(88,  'Ellwood Ahren',  'eahren2f@goodreads.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(89,  'Perri Gladtbach',  'pgladtbach2g@earthlink.net')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(90,  'Garth Clampton',  'gclampton2h@nyu.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(91,  'Ced Beernt',  'cbeernt2i@upenn.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(92,  'Fredelia Sandcroft',  'fsandcroft2j@netvibes.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(93,  'Philip Wasiela',  'pwasiela2k@home.pl')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(94,  'Trudie Fearon',  'tfearon2l@pen.io')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(95,  'Elnore Skuce',  'eskuce2m@sun.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(96,  'Mordecai Pallas',  'mpallas2n@msn.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(97,  'Odelinda Saladin',  'osaladin2o@msu.edu')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(98,  'Candis Varfalameev',  'cvarfalameev2p@auda.org.au')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(99,  'Blondell Parzis',  'bparzis2q@gravatar.com')
INSERT INTO MITARBEITER(ID, NAME, EMAIL) VALUES(100,  'Dorey Cranmore',  'dcranmore2r@devhub.com')




INSERT INTO PROJEKT(ID, NAME, START, END, KOSTEN) VALUES(1, 'Einführung CRM', '2020-03-01', '2020-12-31', 1000000)
INSERT INTO PROJEKT(ID, NAME, START, END, KOSTEN) VALUES(2, 'Entwicklung neuer Geschäftsstrategie', '2018-05-01', '2018-08-30', 50000)
INSERT INTO PROJEKT(ID, NAME, START, END, KOSTEN) VALUES(3, 'Umzug in neuen Geschäftssitz', '2020-07-01', '2020-09-30', 3000000)
INSERT INTO PROJEKT(ID, NAME, START, END, KOSTEN) VALUES(4, 'Evaluation Kaffeemaschinen', '2019-05-01', '2019-05-30', 10000)
INSERT INTO PROJEKT(ID, NAME, START, END, KOSTEN) VALUES(5, 'Ausbau Nebengebäude', '2019-01-01', '2020-12-31', 2500000)
INSERT INTO PROJEKT(ID, NAME, START, END, KOSTEN) VALUES(6, 'Aufbau eines Process CoE', '2020-01-01', '2020-12-31', 500000)
INSERT INTO PROJEKT(ID, NAME, START, END, KOSTEN) VALUES(7, 'Alle aktuellen Buzzwords implementieren', '1990-01-01', '2050-12-31', 500000000)





INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(1, 3, 1, '2020-03-01', '2020-12-31')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(2, 6, 2, '2018-05-01', '2018-08-30')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(3, 9, 3, '2020-07-01', '2020-09-30')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(4, 12, 4, '2019-05-01', '2019-05-30')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(5, 15, 5, '2019-01-01', '2020-12-31')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(6, 18, 6, '2020-01-01', '2020-12-31')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(7, 21, 7, '2018-01-01', '2040-12-31')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(8, 2, 1, '2020-03-31', '2020-12-01')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(9, 5, 2, '2018-05-31', '2018-07-31')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(10, 8, 3, '2020-07-31', '2020-08-31')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(11, 11, 4, '2019-05-31', '2019-04-30')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(12, 14, 5, '2019-01-31', '2020-12-01')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(13, 17, 6, '2020-01-31', '2020-12-01')
INSERT INTO EINSATZ(ID, MITARBEITER_ID, PROJEKT_ID, EINSATZ_START, EINSATZ_ENDE) VALUES(14, 20, 7, '2018-01-31', '2040-12-01')
